export const MOCK_CATEGORIES = [
  { _id: 'cat_men', name: 'Men', slug: 'men', gender: 'men', isActive: true },
  { _id: 'cat_women', name: 'Women', slug: 'women', gender: 'women', isActive: true },
  { _id: 'cat_tshirts', name: 'T-Shirts', slug: 't-shirts', gender: 'men', isActive: true },
  { _id: 'cat_shirts', name: 'Shirts', slug: 'shirts', gender: 'men', isActive: true },
  { _id: 'cat_jeans', name: 'Jeans', slug: 'jeans', gender: 'men', isActive: true },
  { _id: 'cat_dresses', name: 'Dresses', slug: 'dresses', gender: 'women', isActive: true },
  { _id: 'cat_kurtis', name: 'Kurtis', slug: 'kurtis', gender: 'women', isActive: true },
];

export const MOCK_BRANDS = [
  { _id: 'b1', name: 'Thankless Original', slug: 'thankless-original', isActive: true },
  { _id: 'b2', name: 'Fabindia', slug: 'fabindia', isActive: true },
  { _id: 'b3', name: 'Allen Solly', slug: 'allen-solly', isActive: true },
];

const img = (q) => `https://images.unsplash.com/photo-${q}?w=600&h=800&fit=crop`;

export const MOCK_PRODUCTS = [
  {
    _id: 'p1',
    name: 'Classic White Cotton T-Shirt',
    slug: 'classic-white-cotton-t-shirt',
    description: 'Premium 100% cotton t-shirt with a comfortable regular fit. Perfect for everyday wear.',
    shortDescription: 'Premium 100% cotton, regular fit',
    price: 799,
    comparePrice: 1299,
    discount: 38,
    category: MOCK_CATEGORIES[2],
    brand: MOCK_BRANDS[0],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'White', hex: '#ffffff' }, { name: 'Black', hex: '#000000' }],
    stock: 150,
    images: [{ url: img('1521572163474-6864f9cf17ab'), isMain: true }],
    ratings: 4.5,
    numReviews: 128,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
  },
  {
    _id: 'p2',
    name: 'Elegant Silk Saree - Royal Blue',
    slug: 'elegant-silk-saree-royal-blue',
    description: 'Handwoven pure silk saree with intricate golden zari work. A timeless piece for festive occasions.',
    shortDescription: 'Pure silk, handwoven with golden zari',
    price: 4999,
    comparePrice: 7999,
    discount: 37,
    category: MOCK_CATEGORIES[1],
    brand: MOCK_BRANDS[1],
    sizes: ['Free Size'],
    colors: [{ name: 'Royal Blue', hex: '#4169e1' }],
    stock: 45,
    images: [{ url: img('1610030469983-98e550d6193c'), isMain: true }],
    ratings: 4.8,
    numReviews: 256,
    isNewArrival: true,
    isFeatured: true,
    isActive: true,
  },
  {
    _id: 'p3',
    name: 'Slim Fit Stretch Jeans',
    slug: 'slim-fit-stretch-jeans',
    description: 'Modern slim fit jeans made from premium stretch denim for maximum comfort and style.',
    shortDescription: 'Premium stretch denim, slim fit',
    price: 1599,
    comparePrice: 2499,
    discount: 36,
    category: MOCK_CATEGORIES[4],
    brand: MOCK_BRANDS[2],
    sizes: ['30', '32', '34', '36'],
    colors: [{ name: 'Dark Blue', hex: '#00008b' }],
    stock: 200,
    images: [{ url: img('1542272604-787c3835535d'), isMain: true }],
    ratings: 4.3,
    numReviews: 89,
    isBestSeller: true,
    isActive: true,
  },
  {
    _id: 'p4',
    name: 'Floral Printed Kurti',
    slug: 'floral-printed-kurti',
    description: 'Beautiful floral printed kurti in soft cotton fabric. Perfect for both casual and semi-formal occasions.',
    shortDescription: 'Soft cotton, floral print',
    price: 899,
    comparePrice: 1499,
    discount: 40,
    category: MOCK_CATEGORIES[6],
    brand: MOCK_BRANDS[1],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Pink', hex: '#ffc0cb' }],
    stock: 120,
    images: [{ url: img('1608748010899-18f300247112'), isMain: true }],
    ratings: 4.6,
    numReviews: 203,
    isNewArrival: true,
    isBestSeller: true,
    isFlashSale: true,
    isActive: true,
  },
  {
    _id: 'p5',
    name: 'Men\'s Formal Oxford Shirt',
    slug: 'mens-formal-oxford-shirt',
    description: 'Classic Oxford weave formal shirt. Perfect for office wear and formal occasions.',
    shortDescription: 'Oxford weave, slim fit',
    price: 1299,
    comparePrice: 1999,
    discount: 35,
    category: MOCK_CATEGORIES[3],
    brand: MOCK_BRANDS[2],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Blue', hex: '#0000ff' }],
    stock: 80,
    images: [{ url: img('1503341504253-dff4815485f1'), isMain: true }],
    ratings: 4.4,
    numReviews: 67,
    isFeatured: true,
    isActive: true,
  },
  {
    _id: 'p6',
    name: 'Bohemian Wrap Dress',
    slug: 'bohemian-wrap-dress',
    description: 'Elegant wrap dress with bohemian prints. Flattering silhouette for all body types.',
    shortDescription: 'Wrap style, bohemian print',
    price: 1999,
    comparePrice: 3499,
    discount: 43,
    category: MOCK_CATEGORIES[5],
    brand: MOCK_BRANDS[1],
    sizes: ['S', 'M', 'L'],
    colors: [{ name: 'Multicolor', hex: '#ff69b4' }],
    stock: 60,
    images: [{ url: img('1595777457583-95e059d581b8'), isMain: true }],
    ratings: 4.7,
    numReviews: 145,
    isNewArrival: true,
    isActive: true,
  }
];
